### ISSUE TITLE
Pointer Arithmetic - Difference Produces Unexpected Value

### ISSUE THREAD

**Issue by JonBoyleCoding** [gingerBill/Odin#11] opened 2017-01-24 22:51 UTC
While writing a test program, I came across some behaviour when doing pointer arithmetic. Trying to minus one pointer from another ended up with a value that wasn't correct (at least, wasn't what I expected). I produced a test program to see if I could reproduce it, and I could.

Here's the program.

```
#import "fmt.odin";

main :: proc()
{
	b : [1000]byte;

	using fmt;

	println();
	println("Pointer of Address 0");
	println(^b[0]);
	println();
	println("Pointer of Address 50");
	println(^b[50]);
	println();
	println("Difference between 50 and 0");
	println(^b[50] - ^b[0]);
}
```

And the result for 50 - 0 was...

![image](https://cloud.githubusercontent.com/assets/630329/22270328/e997f636-e286-11e6-980c-80a4692477f8.png)

... 6. Not quite the result I was expecting. I wasn't able to cast them to numbers that I could manipulate either.

**Comment by haferburg** [comment] 2017-01-25 07:57
Have you tried `println((^b[50]) - (^b[0]));`?

**Comment by JonBoyleCoding** [comment] 2017-01-25 13:41
Just tried it, it made no difference.

**Comment by gingerBill** [comment] 2017-01-26 17:40
This has now been fixed in the latest commit. The bug was caused by not calculating the pointers "element" size correctly.

**Closed by gingerBill** 2017-01-26 17:40 UTC
