### ISSUE TITLE
LLVM Error when returning a ? type

### ISSUE THREAD

**Issue by JonBoyleCoding** [gingerBill/Odin#10] opened 2017-01-19 22:24 UTC
I was just trying to implement some basic 'file' reading (actually stdin) functionality just for my own testing of the language, and was thinking about how one could use your ? 'maybe' functionality.

My goal was to write a function that returns a ?byte instead of having to return an EOF like in the C fgetc implementation.

```
#import "fmt.odin";
#import "os.odin";

fgetc :: proc(fd : os.Handle) -> ?byte
{
	c : [1]byte;

	if bytes_read, _ := os.read(fd, c[:]); bytes_read == 0
	{
		return nil;
	}

	return c[0];
}

main :: proc ()
{
	b := fgetc(os.stdin);

	if bv, ok := b?; ok
	{
		fmt.println(b);
	}
}
```

However, when compiling, I end up with the following (llvm?) error

> test.ll:1128:9: error: expected type
>         store  zeroinitializer, * %19

I believe the relevant segment in the LLVM bytecode is as follows:
```
if.then-1:
	; ReturnStmt
	store {i8, i1} zeroinitializer, {i8, i1}* %4
	%19 = getelementptr inbounds {i8, i1}, {i8, i1}* %4, i64 0, i32 0
	%20 = getelementptr inbounds {i8, i1}, {i8, i1}* %4, i64 0, i32 1
	store  zeroinitializer, * %19
	store i1 true, i1* %20
	%21 = load {i8, i1}, {i8, i1}* %4, align 1
	ret {i8, i1} %21
```

**Comment by gingerBill** [comment] 2017-01-20 00:22
This is now fixed. It was caused by a printing error in ir_print.c

**Closed by gingerBill** 2017-01-20 00:22 UTC
